# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  roles:

  - role: mafalb.tls.ca
    alias: testca1
    x509_cn: Test CA 1
    x509_organization: Test CA Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT

  - role: mafalb.tls.key
    alias: testcert1.example.com
   
  - role: mafalb.tls.csr
    alias: testcert1.example.com
    x509_cn: testcert1.example.com
    x509_organization: Test Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT
  
  tasks:
  
  - name: testcert.example.com cert is present
    openssl_certificate:
      path: "{{ tls_default_cert_dir }}/testcert1.example.com.cert"
      csr_path: "{{ tls_default_cert_dir }}/testcert1.example.com.csr"
      ownca_path: "{{ tls_default_cert_dir }}/testca1.cert"
      ownca_privatekey_path: "{{ tls_default_private_dir }}/testca1.key"
      provider: ownca

  - name: fetch the certificate 
    loop:
    - "{{ tls_default_cert_dir }}/testcert1.example.com.cert"
    - "{{ tls_default_cert_dir }}/testca1.cert"
    fetch:
      src: "{{ item }}"
      flat: true
      dest: files/testca1

  - name: deploy the certificate
    include_role:
      name: mafalb.tls.certificate
    vars:
      alias: anothercert1.example.com
      cert: files/testca1/testcert1.example.com.cert
      key: testcert1.example.com.key
      root:
      - files/testca1/testca1.cert
...
