# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  roles:

  - role: mafalb.tls.ca
    alias: Root_CA_1
    x509_cn: Root CA 1
    x509_organization: Test CA Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT

  - role: mafalb.tls.ca
    alias: Signing_CA_1
    x509_cn: Signing CA 1
    x509_organization: Test CA Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT
    signing_key: Root_CA_1.key
    signing_cert: Root_CA_1.cert

  - role: mafalb.tls.key
    alias: testcert1.example.com
   
  - role: mafalb.tls.csr
    alias: testcert1.example.com
    x509_cn: testcert1.example.com
    x509_organization: Test Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT
  
  tasks:
  
  - name: testcert.example.com cert is present
    openssl_certificate:
      path: "{{ tls_default_cert_dir }}/testcert1.example.com.cert"
      csr_path: "{{ tls_default_cert_dir }}/testcert1.example.com.csr"
      ownca_path: "{{ tls_default_cert_dir }}/Signing_CA_1.cert"
      ownca_privatekey_path: "{{ tls_default_key_dir }}/Signing_CA_1.key"
      provider: ownca

  - name: fetch the certificate 
    loop:
    - "{{ tls_default_cert_dir }}/testcert1.example.com.cert"
    - "{{ tls_default_cert_dir }}/Signing_CA_1.cert"
    - "{{ tls_default_cert_dir }}/Root_CA_1.cert"
    fetch:
      src: "{{ item }}"
      flat: true
      dest: files/testca1/{{ item|basename }}

  - name: deploy the certificate
    include_role:
      name: mafalb.tls.certificate
    vars:
      alias: anothercert1.example.com
      cert: files/testca1/testcert1.example.com.cert
      key: testcert1.example.com.key
      chain:
      - files/testca1/Signing_CA_1.cert
      root:
      - files/testca1/Root_CA_1.cert
...
