# vim: set ft=yaml ts=2 expandtab:
---

- hosts: localhost
  tasks:

  - openssl_certificate_info:
      path: /etc/pki/tls/certs/www.s-versicherung-online.at.cert
    register: _cert_info

  - debug:
      var=_cert_info

  - debug:
      msg: "{{ (_cert_info.not_after[:-1]|to_datetime('%Y%m%d%H%M%S') - _cert_info.not_before[:-1]|to_datetime('%Y%m%d%H%M%S')).days }}"

  - assert:
      that:
      - (_cert_info.not_after[:-1]|to_datetime('%Y%m%d%H%M%S') - _cert_info.not_before[:-1]|to_datetime('%Y%m%d%H%M%S')).days == 414

...
