# vim: set ft=yaml ts=2 expandtab:
---

- name: openssl is installed
  package:
    name: openssl

- name: OS specific variables
  include_vars:
      file: "{{ ansible_os_family }}.yml"

- name: assertions
  assert:
    that:
    - key_file|default(tls_default_private_dir) is defined
    - csr_dir|default(tls_default_cert_dir) is defined
    - alias is defined

- name: assert that certificate info is present
  assert:
    that:
    - x509_cn is defined
    - x509_organization is defined
    - x509_locality is defined
    - x509_province is defined
    - x509_country is defined

- name: check x509_sans
  when: x509_sans is defined
  block:

  - assert:
      that:
      - x509_sans|type_debug == 'list'

  - name: check x509_sans
    with_items: "{{ x509_sans }}"
    assert:
      that:
      - x509_cn != item

- name: assertions for x509_extended_key_usage
  when: x509_extended_key_usage is defined
  block:

  - name: x509_extended_key_usage is a list
    assert:
      that:
      - x509_extended_key_usage|type_debug == 'list'

  - name: x509_extended_key_usage is valid
    with_items: "{{ x509_extended_key_usage }}"
    assert:
      that:
      - item in openssl_extended_key_usages

- name: directory for csr does exist
  when:
  - csr_dir is defined or alias|dirname != ""
  file:
    path: "{{ csr_dir|default(tls_default_cert_dir) }}/{{ alias|dirname }}"
    state: directory
    recurse: true

- name: CSR config is present
  with_first_found:
    - "{{ csr_config_file|default(omit) }}"
    - csr.cnf.j2
  template:
    src: "{{ item }}"
    dest: "{{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.cnf"

- name: CSR is present (existing will be overwritten)
  when: csr_overwrite is defined
  command: openssl req -new -utf8 -key {{ key_file|default(tls_default_private_dir + '/' + alias + '.key') }} -out {{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr -config {{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.cnf

- name: CSR is present
  when: csr_overwrite is not defined
  command: openssl req -new -utf8 -key {{ key_file|default(tls_default_private_dir + '/' + alias + '.key') }} -out {{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr -config {{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.cnf
  args:
    creates: "{{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr"

- name: CSR matches key
  block:

  - name: get modulus of CSR
    command: openssl req -modulus -in {{ csr_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr -noout
    register: _csr_modulus
    changed_when: false
    check_mode: false
  
  - name: get modulus of test1.example.com key
    command: openssl rsa -modulus -in {{ key_file|default(tls_default_private_dir + '/' + alias + '.key') }}  -noout
    register: _key_modulus
    changed_when: false
    check_mode: false
  
  - name: Assertions
    assert:
      that:
      - _csr_modulus.stdout == _key_modulus.stdout

...
