# vim: set ft=yaml ts=2 expandtab:
---

- name: get modulus of {{ csr }}
  command: openssl req -modulus -in {{ csr }} -noout
  register: _csr_modulus
  changed_when: false
  check_mode: false

- name: Assertions for {{ csr }}
  assert:
    that:
    - _csr_modulus.stdout == _key_modulus.stdout

...
