# vim: set ft=yaml ts=2 expandtab:
---

- name: verify CSR
  when:
  - csr is defined
  - key is defined
  include_tasks:
    file: csr.yml

- name: verify cert
  when:
  - cert is defined
  - key is defined
  include_tasks:
    file: cert.yml

...
