# vim: set ft=yaml ts=2 expandtab:
---

- name: OS specific config
  include_role:
    name: mafalb.tls.cfg
    public: true

- name: assertions
  assert:
    that:
      - cert_dir|default(tls_default_cert_dir) is defined
      - private_dir|default(tls_default_key_dir) is defined
      - alias is defined

- name: CA privatekey is present
  include_role:
    name: mafalb.tls.key

- name: CA CSR is present
  include_role:
    name: mafalb.tls.csr
  vars:
    ca: true

- name: Root CA certificate is present
  when: signing_key is not defined
  openssl_certificate:
    path: "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.cert"
    privatekey_path: "{{ private_dir|default(tls_default_key_dir) }}/{{ alias }}.key"
    csr_path: "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr"
    provider: selfsigned

- name: Intermediate certificate is present
  when: signing_key is defined
  openssl_certificate:
    path: "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.cert"
    ownca_path: "{{ cert_dir|default(tls_default_cert_dir) }}/{{ signing_cert }}"
    ownca_privatekey_path: "{{ private_dir|default(tls_default_key_dir) }}/{{ signing_key }}"
    csr_path: "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr"
    provider: ownca

...
