# vim: set ft=yaml ts=2 expandtab:
---

- name: files for {{ alias }} are absent
  loop:
  - "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.cert"
  - "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.chain.pem"
  - "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.root.pem"
  - "{{ key_dir|default(tls_default_key_dir) }}/{{ alias }}.key"
  - "{{ key_dir|default(tls_default_key_dir) }}/{{ alias }}.pem }}"
  - "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.csr"
  - "{{ cert_dir|default(tls_default_cert_dir) }}/{{ alias }}.cnf"
  file:
    path: "{{ item }}"
    state: absent

# the root certificates need special treating because
# we dont know how many are present
#
- block:

  - name: find root certificates
    find:
      paths: "{{ cert_dir|default(tls_default_cert_dir) }}"
      patterns: "{{ alias }}.root?.cert"
    register: _files_to_delete

  - name: debug
    debug:
      var: _files_to_delete
    tags:
    - never
    - debug

  - name: root certificates are absent
    loop: "{{ _files_to_delete.files }}"
    file:
      path: "{{ item.path }}"
      state: absent

...
