# vim: set ft=yaml ts=2 expandtab:
---

- debug: var=playbook_dir
  tags:
  - never
  - debug

- name: include_tasks for {{ alias }}
  include_tasks:
    file: "{{ state|default('present') }}.yml"

...
