# vim: set ft=yaml ts=2 expandtab:
---

- name: debug
  debug: var=playbook_dir
  tags:
  - never
  - debug

- name: include_tasks for {{ alias }}
  include_tasks: "{{ state|default('present') }}.yml"

...
