# vim: set ft=yaml ts=2 expandtab:
---

- debug: var=playbook_dir
  tags:
  - never
  - debug

- name: OS specific config
  include_role:
    name: mafalb.tls.cfg
    public: true

- name: include_tasks
  include_tasks:
    file: "{{ state|default('present') }}.yml"

...
