# vim: set ft=yaml ts=2 expandtab:
---

- name: dependencies
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:
  - role: mafalb.ansible.node
  - role: mafalb.tls.cfg

- name: create key
  hosts: all,!ca
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:

  - role: mafalb.tls.key
    alias: test1.example.com-20200114

  - role: mafalb.tls.key
    alias: another_keydir/test2.example.com-20200114

  - role: mafalb.tls.key
    alias: test3.example.com-20200114
    key_dir: /tmp

  - role: mafalb.tls.key
    alias: key/blubb/test4.example.com-20200114
    key_dir: /tmp

- name: create key for cluster
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:
  - role: mafalb.tls.key
    alias: clusterkey.example.com
    one_key_for_all: true

- name: create keys on multiple hosts - no cluster
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:

  - role: mafalb.tls.key
    alias: nonclusterkey.example.com

- name: Converge csr
  hosts: all,!ca
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:

  - role: mafalb.tls.csr
    alias: test1.example.com-20200114
    x509_cn: test1.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT
    x509_sans:
    - example.com

  - role: mafalb.tls.csr
    alias: another_csrdir/test2.example.com-20200114
    key_file: another_keydir/test2.example.com-20200114.key
    x509_cn: test2.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

  - role: mafalb.tls.csr
    alias: testkey
    key_file: /tmp/test3.example.com-20200114.key
    x509_cn: test1
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

  - role: mafalb.tls.csr
    alias: test3.example.com-20200114
    csr_dir: /tmp/another/csrdir
    key_file: /tmp/test3.example.com-20200114.key
    x509_cn: test3.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

  - role: mafalb.tls.csr
    alias: test4.example.com-20200114
    key_file: /tmp/key/blubb/test4.example.com-20200114.key
    x509_cn: test4.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

- name: create CA
  hosts: all,!t_centos6
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:

  - role: mafalb.tls.ca
    alias: root_ca_1
    x509_cn: Root CA 1
    x509_organization: Test CA Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT
    key_dir: /tmp/root_ca_1
    csr_dir: /tmp/root_ca_1
    cert_dir: /tmp/root_ca_1
    ca_days: 3650

  - role: mafalb.tls.ca
    alias: signing_ca_1
    x509_cn: Signing CA 1
    x509_organization: Test CA Organization
    x509_locality: Wien
    x509_province: Wien
    x509_country: AT
    signing_key: /tmp/root_ca_1/root_ca_1.key
    signing_cert: /tmp/root_ca_1/root_ca_1.cert
    key_dir: /tmp/signing_ca_1
    csr_dir: /tmp/signing_ca_1
    cert_dir: /tmp/signing_ca_1
    ca_days: 400


- name: test3.example.com
  hosts: all,!ca,!t_centos6
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:

  - name: test3.example.com cert is present
    openssl_certificate:
      path: "{{ tls_default_cert_dir }}/test3.example.com.cert"
      csr_path: /tmp/another/csrdir/test3.example.com-20200114.csr
      ownca_path: /tmp/signing_ca_1/signing_ca_1.cert
      ownca_privatekey_path: /tmp/signing_ca_1/signing_ca_1.key
      provider: ownca
      ownca_not_after: +825d


- name: test1.example.com
  hosts: all,!ca
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:

  - name: fetch the csr
    fetch:
      src: "{{ tls_default_cert_dir }}/test1.example.com-20200114.csr"
      flat: true
      dest: files/testcert2/{{ ansible_hostname }}/test1.example.com-20200114.csr

  - name: create per hostname directory
    delegate_to: t_CA
    file:
      path: /tmp/signing_ca_1/{{ ansible_hostname }}
      state: directory

  - name: copy the csr to CA
    delegate_to: t_CA
    copy:
      src: files/testcert2/{{ ansible_hostname }}/test1.example.com-20200114.csr
      dest: /tmp/signing_ca_1/{{ ansible_hostname }}/

  - name: test1.example.com cert is present
    delegate_to: t_CA
    openssl_certificate:
      path: /tmp/signing_ca_1/{{ ansible_hostname }}/test1.example.com.cert
      csr_path: /tmp/signing_ca_1/{{ ansible_hostname }}/test1.example.com-20200114.csr
      ownca_path: /tmp/signing_ca_1/signing_ca_1.cert
      ownca_privatekey_path: /tmp/signing_ca_1/signing_ca_1.key
      provider: ownca
      ownca_not_after: +825d

- name: Converge test1.example.com
  hosts: all,!ca
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  pre_tasks:

  - name: fetch the certificate
    delegate_to: t_CA
    loop:
    - /tmp/signing_ca_1/{{ ansible_hostname }}/test1.example.com.cert
    - /tmp/signing_ca_1/signing_ca_1.cert
    - /tmp/root_ca_1/root_ca_1.cert
    fetch:
      src: "{{ item }}"
      flat: true
      dest: files/testcert1/{{ ansible_hostname }}/{{ item|basename }}

  roles:

  - role: mafalb.tls.certificate
    alias: test1.example.com
    cert: files/testcert1/{{ ansible_hostname }}/test1.example.com.cert
    key: test1.example.com-20200114.key
    chain:
    - files/testcert1/{{ ansible_hostname }}/signing_ca_1.cert
    root:
    - files/testcert1/{{ ansible_hostname }}/root_ca_1.cert

  - role: mafalb.tls.certificate
    alias: test1_1.example.com
    remote_cert: test1.example.com.cert
    key: test1.example.com-20200114.key
    remote_chain:
    - test1.example.com.chain.pem
    root:
    - files/testcert1/{{ ansible_hostname }}/root_ca_1.cert

  - role: mafalb.tls.certificate
    alias: test1_2.example.com
    remote_cert: test1.example.com.cert
    remote_key: test1_1.example.com.key
    remote_chain:
    - test1.example.com.chain.pem
    root:
    - files/testcert1/{{ ansible_hostname }}/root_ca_1.cert

  - role: mafalb.tls.certificate
    alias: test1_3.example.com
    remote_cert: test1.example.com.cert
    remote_key: test1_1.example.com.key
    remote_chain:
    - test1.example.com.chain.pem
    root:
    - files/testcert1/{{ ansible_hostname }}/root_ca_1.cert
    state: present

...
