# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: t_centos6
    image: centos:6
  - name: t_centos7
    image: centos:7
  - name: t_centos8
    image: centos:8
  - name: t_ubuntu16
    image: ubuntu:xenial
  - name: t_ubuntu18
    image: ubuntu:bionic
  - name: t_ubuntu20
    image: ubuntu:focal
  - name: t_CA
    image: centos:8
    groups:
    - ca
#  - name: t_rawhide
#    image: fedora:rawhide

provisioner:
  name: ansible
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
  inventory:
    host_vars:
      t_CA:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
  lint:
    name: ansible-lint

...
