# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
  options:
    role-file: idontexist.yml   # avoid warning while running molecule
    requirements-file: molecule/default/requirements.yml

driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  ansible-lint -v roles/*/vars/*.yml
  tests/check-README.sh
  flake8 -v

platforms:
  - name: ${CI_HOSTNAME-"ci-rocky8"}
    image: ${CI_IMAGE:-"quay.io/rockylinux/rockylinux:8"}
    dockerfile: ${CI_DOCKERFILE:-Dockerfile.j2}
    groups:
    - ci_group
  - name: ci-CA
    image: quay.io/rockylinux/rockylinux:8
    groups:
    - ca_group

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
    - -vvv
  config_options:
    defaults:
      gathering: smart
      interpreter_python: auto
  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
