---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: t_centos6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
verifier:
  name: ansible
  lint:
    name: ansible-lint
