# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  ansible-lint -v vars/*.yml
  flake8 -v

platforms:
  - name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
    image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}
    dockerfile: ${CI_DOCKERFILE:-Dockerfile.j2}
  - name: t_CA
    image: centos:8
    groups:
    - ca

#  - name: t_ubuntu20
#    image: ubuntu:focal
#  - name: t_rawhide
#    image: fedora:rawhide

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
  inventory:
    host_vars:
      t_CA:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
  lint:
    name: ansible-lint

...
