# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:

  - role: mafalb.tls.key
    alias: test1.example.com-20200114

  - role: mafalb.tls.key
    alias: another_keydir/test2.example.com-20200114

  - role: mafalb.tls.key
    alias: test3.example.com-20200114
    key_dir: /tmp

  - role: mafalb.tls.key
    alias: key/blubb/test4.example.com-20200114
    key_dir: /tmp

  - role: mafalb.tls.csr
    alias: test1.example.com-20200114
    x509_cn: test1.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT
    x509_sans:
    - example.com

  - role: mafalb.tls.csr
    alias: another_csrdir/test2.example.com-20200114
    key_file: "{{ tls_default_key_dir }}/another_keydir/test2.example.com-20200114.key"
    x509_cn: test2.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

  - role: mafalb.tls.csr
    alias: test3.example.com-20200114
    csr_dir: /tmp/another/csrdir
    key_file: /tmp/test3.example.com-20200114
    x509_cn: test3.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

  - role: mafalb.tls.csr
    alias: test4.example.com-20200114
    key_file: /tmp/key/blubb/test4.example.com-20200114.key
    x509_cn: test4.example.com
    x509_organization: bla
    x509_locality: Vienna
    x509_province: Vienna
    x509_country: AT

...
