# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all

  vars:
    __default_private_dir:
      Debian: /etc/ssl/private
      RedHat: /etc/pki/tls/private
    __default_cert_dir:
      Debian: /etc/ssl/certs
      RedHat: /etc/pki/tls/certs

  roles:

  - name: verify test1.example.com-20200114
    role: mafalb.tls.verify
    csr: "{{ __default_cert_dir[ansible_os_family] }}/test1.example.com-20200114.csr"
    key: "{{ __default_private_dir[ansible_os_family] }}/test1.example.com-20200114.key"

  - name: verify another_keydir/test2.example.com-20200114
    role: mafalb.tls.verify
    csr: "{{ __default_cert_dir[ansible_os_family] }}/another_csrdir/test2.example.com-20200114.csr"
    key: "{{ __default_private_dir[ansible_os_family] }}/another_keydir/test2.example.com-20200114.key"

  - name: verify test3.example.com-20200114
    role: mafalb.tls.verify
    csr: /tmp/another/csrdir/test3.example.com-20200114.csr
    key: "{{ __default_private_dir[ansible_os_family] }}/test3.example.com-20200114.key"

  - name: verify key/blubb/test4.example.com-20200114
    role: mafalb.tls.verify
    csr: "{{ __default_cert_dir[ansible_os_family] }}/test4.example.com-20200114.csr"
    key: tmp/key/blubb/test4.example.com-20200114.key

...
