# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify key and csr
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:

  - name: OS specific config
    role: mafalb.tls.cfg

  - name: verify test1.example.com-20200114
    role: mafalb.tls.verify
    csr: "{{ default_cert_dir }}/test1.example.com-20200114.csr"
    key: "{{ default_key_dir }}/test1.example.com-20200114.key"

  - name: verify another_keydir/test2.example.com-20200114
    role: mafalb.tls.verify
    csr: "{{ default_cert_dir }}/another_csrdir/test2.example.com-20200114.csr"
    key: "{{ default_key_dir }}/another_keydir/test2.example.com-20200114.key"

  - name: verify testkey
    role: mafalb.tls.verify
    csr: "{{ default_cert_dir }}/testkey.csr"
    key: "{{ default_key_dir }}/test3.example.com-20200114.key"

  - name: verify test3.example.com-20200114
    role: mafalb.tls.verify
    csr: /tmp/another/csrdir/test3.example.com-20200114.csr
    key: /tmp/test3.example.com-20200114.key

  - name: verify key/blubb/test4.example.com-20200114
    role: mafalb.tls.verify
    csr: "{{ default_cert_dir }}/test4.example.com-20200114.csr"
    key: /tmp/key/blubb/test4.example.com-20200114.key

- name: CA
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:

  - name: verify root_ca_1
    role: mafalb.tls.verify
    csr: /tmp/root_ca_1/root_ca_1.csr
    key: /tmp/root_ca_1/root_ca_1.key
    cert: /tmp/root_ca_1/root_ca_1.cert

  - name: verify signing_ca_1
    role: mafalb.tls.verify
    csr: /tmp/signing_ca_1/signing_ca_1.csr
    key: /tmp/signing_ca_1/signing_ca_1.key
    cert: /tmp/signing_ca_1/signing_ca_1.cert
  
...
