# vim: set ft=yaml ts=2 expandtab:
---

- name: OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: assertions
  assert:
    that:
    - key_dir|default(tls_default_private_dir) is defined
    - alias is defined
    - key_size is defined
    - key_type in ['RSA']

- name: directory for {{ alias }} is present
  when:
  - key_dir is defined or alias|dirname != ""
  file:
    path: "{{ key_dir|default(tls_default_private_dir) }}/{{ alias|dirname }}"
    state: directory
    recurse: true

- name: dependencies are installed
  include_role:
    name: mafalb.ansible.node

- name: "{{ alias }} is present"
  openssl_privatekey:
    path: "{{ key_dir|default(tls_default_private_dir) }}/{{ alias }}.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    backup: true

...
