# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  assert:
    that:
    - key_dir|default(tls_default_key_dir) is defined
    - alias is defined
    - key_size is defined
    - key_type in ['RSA']

- debug:
    var: alias
  tags:
  - never
  - debug

- debug:
    var: alias2
  tags:
  - never
  - debug

- name: directory for {{ alias }} is present
  when:
  - key_dir is defined or alias|dirname != ""
  file:
    path: "{{ key_dir|default(tls_default_key_dir) }}/{{ alias|dirname }}"
    state: directory
    recurse: true

- name: "{{ alias }} is present"
  openssl_privatekey:
    path: "{{ key_dir|default(tls_default_key_dir) }}/{{ alias }}.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    backup: true

...
