# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  push:
  pull_request:  
  schedule:
  - cron: '40 12 * * 6'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

      - name: checkout collection
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/tls
      
      - name: install mafalb.tls
        run: ansible-galaxy collection install mafalb.tls

      - name: install molecule
        run: ansible-playbook -D install_molecule.yml

      - name: build test images
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          PY_COLORS=1 molecule create

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 molecule test

...
