# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  push:
  schedule:
  - cron: '40 12 * * 6'

jobs:
  tls:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos_7
        - centos_8
        - centos_6
        - ubuntu_1804
        - ubuntu_1604
        - ubuntu_2004
        - fedora_31
        - fedora_32

        ansible_version:
        - '2.10'
        - '2.9'

        include:

        - target: centos_7
          distribution: centos
          version: 7

        - target: centos_8
          distribution: centos
          version: 8

        - target: centos_6
          distribution: centos
          version: 6

        - target: ubuntu_1804
          distribution: ubuntu
          version: bionic

        - target: ubuntu_1604
          distribution: ubuntu
          version: xenial

        - target: ubuntu_2004
          distribution: ubuntu
          version: focal

        - target: fedora_31
          distribution: fedora
          version: 31

        - target: fedora_32
          distribution: fedora
          version: 32

    env:
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
      CI_CONTAINER_PRIVILEGED: true
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}

    defaults:
      run:
        working-directory: ansible_collections/mafalb/tls

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/tls
      
      - name: checkout collection
        if: false
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/ansible
          repository: mafalb/ansible-collection-ansible
          ref: dev

      - name: mv ansible
        if: false
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/mafalb
          mv ansible_collections/mafalb/ansible ~/.ansible/collections/ansible_collections/mafalb/

      - name: update apt cache
        run: sudo apt-get update

      - name: install dependencies
        run: ansible-galaxy collection install -r molecule/requirements.yml

      - name: install molecule
        run: ansible-playbook -D molecule/install_molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }}

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 CI_CONTAINER_PRIVILEGED=$CI_CONTAINER_PRIVILEGED CI_CONTAINER_IMAGE=$CI_CONTAINER_IMAGE CI_CONTAINER_TAG=$CI_CONTAINER_TAG molecule --debug test

...
