# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
  - cron: '40 12 * * 6'

jobs:
  tls:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - fedora33
        - fedora34
        - c8s
        - alma8
        - rocky8
        - centos7
        - centos8
        - debian9
        - debian10
        - ubuntu16
        - ubuntu18
        - ubuntu20

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

        include:

        - target: fedora33
          image: docker.io/fedora:33

        - target: fedora34
          image: docker.io/fedora:34

        - target: c8s
          image: quay.io/centos/centos:stream8

        - target: alma8
          image: quay.io/almalinux/almalinux:8

        - target: rocky8
          image: quay.io/rockylinux/rockylinux:8

        - target: centos7
          image: quay.io/centos/centos:7

        - target: centos8
          image: quay.io/centos/centos:8

        - target: debian9
          image: docker.io/debian:stretch

        - target: debian10
          image: docker.io/debian:buster

        - target: ubuntu16
          image: docker.io/ubuntu:xenial

        - target: ubuntu18
          image: docker.io/ubuntu:bionic

        - target: ubuntu20
          image: docker.io/ubuntu:focal

    env:
      
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_IMAGE: ${{ matrix.image }}
      CI_HOSTNAME: ci-${{ matrix.target }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/tls

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/tls
      
      - name: install mafalb.ansible
        run: ansible-galaxy collection install mafalb.ansible

      - name: install molecule
        run: |
          /usr/bin/ansible-playbook -e ansible_python_interpreter python3 -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=$ANSIBLE_VERSION -t all,debug

      - name: check ansible version
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          molecule test

...
