# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  push:
  pull_request:  
  schedule:
  - cron: '40 12 * * 6'

jobs:
  tls:

    runs-on: ubuntu-18.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos_7
        - centos_8
        - centos_6
        - ubuntu_1804
        - ubuntu_1604
        - fedora_31
        - fedora_30

        include:

        - target: centos_7
          distribution: centos
          version: 7

        - target: centos_8
          distribution: centos
          version: 8

        - target: centos_6
          distribution: centos
          version: 6

        - target: ubuntu_1804
          distribution: ubuntu
          version: bionic

        - target: ubuntu_1604
          distribution: ubuntu
          version: xenial

        - target: fedora_31
          distribution: fedora
          version: 31

        - target: fedora_30
          distribution: fedora
          version: 30

    env:
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
      CI_CONTAINER_PRIVILEGED: true

    steps:

      - name: checkout collection
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/tls
      
      - name: install mafalb.ansible
        run: ansible-galaxy collection install mafalb.ansible

      - name: grep for forgotten no_log
        run: '! grep -r "no_log: false" roles'

      - name: install molecule
        run: ansible-playbook -D install_molecule.yml

      - name: manual lint
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible-lint roles/*

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 molecule test
          PY_COLORS=1 CI_CONTAINER_PRIVILEGED=$CI_CONTAINER_PRIVILEGED CI_CONTAINER_IMAGE=$CI_CONTAINER_IMAGE CI_CONTAINER_TAG=$CI_CONTAINER_TAG molecule test

...
